---
- name: Restart gunicorn
  systemd:
    name: ci-cd-app
    state: restarted
    enabled: yes
    daemon_reload: yes

- name: Restart nginx
  systemd:
    name: nginx
    state: restarted
    enabled: yes
